---
title: "Module 5: Standards and Standardization"
subtitle: "LIS 5043: Organization of Information"
author: 
  - Dr. Manika Lamba
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      theme: whiteboard
      buttons: true
    preview-links: true
    controls: true
    progress: true
    show-notes: separate-page
    logo: images/ou.png
    css: styles.css
editor: 
  markdown: 
    wrap: 72
---

# Introduction

::: notes
In Module 5 we’re going to shift gears a little bit and talk about standards and standardization.

Structures for organizing knowledge are not developed in isolation, nor are they developed without a great deal of discussion and collaboration and trial and error by multiple different interested parties. 

Formalized structures for organizing knowledge, such as databases and bibliographic retrieval systems or even subject thesaurus are developed according to national, regional, and international standards. 

So, let’s talk about what standards are and the standard development process. 
:::

## What is a “Standard”?

- A standard, according to the British Standards Institute, is 

"`an agreed, repeatable way of doing something. It is a published document that contains a technical specification or other precise criteria designed to be used consistently as a rule, guidance, or definition`" 

:::notes
There are several different definitions for “standard” and you’ll see some of these in your readings, but the one that I think probably encapsulates this concept the best is one from the British Standards Institute, or the BSI. 

A ‘standard’ is defined according to the British Standards Institute as “an agreed, repeatable way of doing something. It is a published document that contains a technical specification or other precise criteria designed to be used consistently as a rule, guidance, or definition.” 

For example, when we start talking about bibliographic control and bibliographic cataloging in the next module, we’ll learn about the Anglo-American Cataloging Rules. The AACR2 is considered a standard. It’s a content standard. The holder of the cataloging information or the MARC record structure is what we might consider a technical standard. 
:::

## Functions of Standards {.smaller}

**ISO - What Standards Do (2009)**

- Make the development, manufacturing and supply of products and services `more efficient, safer and cleaner`
- `Facilitate trade` between countries and make it `fairer` 
provide governments with a technical base for `health, safety and environmental legislation`, and conformity assessment 
- `Share` technological advances and good management practice 
- Disseminate `innovation`
- `Safeguard consumers`, and users in general, of products and services 
- Make life simpler by `providing solutions` to common problems

:::notes
Standards serve many different functions and purposes depending upon the community in which they serve or that they’re developed within. For example, they make the development, manufacturing, and supply of products and services more efficient, safer, and cleaner. Having standards for the development of different products ensures users as well as governments that those services and products will be developed in a safe, clean environment and that the process will also be more efficient as the result of standards. 

Standards can also facilitate trade between countries and make it fairer because there are specific criteria that must be met. They can provide governments with a technical basis for health, safety, and environmental legislation, as well as conformity assessment, so that governments have guidelines in place for the development of products that ensure health and safety as well as environmental protections.

Standards also help to share technological advances and good management practices. If you are developing bibliographic tools or retrieval tools but you’re not adhering to any specific standards, there may be difficulty in interoperability, meaning that the two systems may not be able to talk to each other or work together. 

Standards also help to disseminate innovation because they encourage the sharing of ideas as well as the following of guidelines to develop new products. In this way, they help to safeguard consumers and users in general because of the production of good, safe, efficient products and services.  

Overall, standards make life simpler by providing solutions to common problems. This synthesis of the function of standards is from the International Standards Organization, or what we call the ISO under their “What Standards Do” page.
:::

## Why Develop Standards?

- Standards can be voluntary or ad hoc and developed for specific purposes or products

- Standards are developed and applied within a multitude of different contexts, from manufacturing, information management, and technology, to agriculture and the sciences

:::notes
Obviously, the functions also show some advantages as to why we would develop standards. 

Standards are developed through either an ad hoc or voluntary process and they can be developed for specific purposes or products. 

Standards are also developed and applied within a multitude of different contexts, from manufacturing and information management and technology to agriculture and the sciences. 

In our program–and in this class in particular–the standards we’re interested in most are the information management and technology standards, and we’ll look at some examples of those throughout the semester. 
:::

## Who Develops Standards? {.smaller}

- Official standards organizations
  - NISO (National Information Standards Organization) 
 - ISO (International Standards Organization) 
- Industry Consortia
  - Unicode Consortium 
  - WC3 (Worldwide Web Consortium) 
- Cooperative Consortia of Universities
- Other Research Organization, or Industrial Organizations or Business Entities 
  - Microsoft and Adobe 

:::notes
So, who develops standards? There are several stakeholders or groups that develop standards. Those that we work with in libraries and information professions are developed by national and international organizations. So there are official standards organizations that develop our standards or those that are related to information management technology that we are most concerned with. 

The first of these organizations is the National Information Standards Organization, or NISO. The second is the International Standards Organization, or ISO. But there are also standards that are developed from industry consortia. An example of one of these is the Unicode Consortia, which developed the Unicode technical standard. Also, the WC3, or the Worldwide Web Consortium, who’ve been instrumental in developing the semantic web. The WC3, for example, is an industry consortia, but it’s also a host of volunteers around the world. 

We also have standards being developed from cooperative consortia or universities. If there’s a particular problem or issue that needs to be addressed, a consortia of universities might be the developing body of that standard.

There are also research organizations or industrial organizations and even business entities that help to develop standards or they’re part of a standards development process. Microsoft, for example, or Adobe, have been very instrumental in developing the standards. Adobe, for example, has been at the forefront for developing a .jpeg standard and the PDF standards.
:::

## Who: American National Standards Institute (ANSI)

**ANSI - Overview of ANSI (2009)**

- `Coordinates` the U.S. voluntary consensus standards system
- `Accredits` qualified organizations, whose standards development process meets all of ANSI’s requirements, to develop American National Standards
- `Represents` U.S. interests in regional and international standardization activities while overseeing conformity assessment activities that promote the global acceptance of U.S. products, services, systems and personnel

:::notes
Another body that is instrumental in developing standards that we use in information management and technology is the American National Standards Institute, or ANSI. ANSI is a unique body because it serves as an accrediting body for standards and standards development. It coordinates the US voluntary consensus standards system. It coordinates all of the voluntary standards development processes in the United States. 

So, if a standard is being developed by an institution or an industry or a university consortia, those might be considered voluntary consensus standard builders, and ANSI is the body that coordinates all of those activities. It also accredits, or it gives its stamp of approval based on its own particular guidelines, to qualified organizations whose standards development processes meet all of ANSI’s requirements to develop American national standards. ANSI only applies to standards developed in the United States.

It also represents US interests in regional and international standardization activities. So, it provides an oversight committee. It oversees conformity assessment activities and promotes global acceptance of US products and services, systems and personnel. 

So, ANSI might be the body that coordinates activities or represents the US interests in international standards development, such as that at the ISO level, or International Standards Organization level. So, ANSI is an interesting body. As I said, they serve as coordination, accrediting, and representative body for American standards.
:::

## Who: National Information Standards Organization (NISO)

**NISO - About NISO (2009)**

- Non-profit association accredited by the American National Standards Institute which "identifies, develops, maintains, and publishes technical standards to manage information in our changing and ever-more digital environment"

- NISO standards apply both traditional and new technologies to the full range of information-related needs, including retrieval, re-purposing, storage, metadata, and preservation

:::notes
NISO, then, or the National Information Standards Organization, is a non-profit association accredited by ANSI, which “identifies, develops, maintains, and publishes technical standards to manage information in an ever-changing digital environment.” NISO is the standards institute that most of library and information profession standards are developed by, but again, it’s not the only one. But it is the primary one in the United States, and they don’t just focus on information management, they develop technical standards as well. 

“NISO standards apply both traditional and new technologies” to aid “the full range of information-related needs,” but they focus primarily on “retrieval, repurposing, storage, metadata, and preservation” issues. You can find that information and more about NISO at the NISO webpage listed on the Readings List. 
:::

## NISO (Cont.) {.smaller}

- NISO's Mission Statement emphasizes their commitment to standards development

- "NISO fosters the development and maintenance of standards that facilitate the creation, persistent management, and effective interchange of information so that it can be trusted for use in research and learning" (NISO, About NISO, 2009) 

- NISO's voting members include industry leaders of over 70 organizations in the fields of publishing, libraries, IT, and media, as well as experts and practitioners who serve on NISO working groups, committees, and as officers of the association

::: notes
NISO’s primary mission, or their mission statement, emphasizes their commitment to standards development. As an information professional, you can become a member of NISO and have voting rights and get involved in the standards development process. 

“NISO [also] fosters the development and maintenance of standards that facilitate the creation, persistent management, and effective interchange of information so that it can be trusted for use in research and learning.” So, a NISO standard, generally if it’s stamped with NISO, allows people to trust that that standard is well-developed and that it can be used in research and in educational contexts without worry. But NISO really does foster the development and maintenance of standards, and that maintenance is an important component of a standards organization because if you develop a standard and then it’s never reviewed or maintained, it can become very ineffectual. 

NISO’s voting members are comprised of various different individuals. These can include people from industry, such as industry leaders, and over seventy different organizations in the field of publishing, in libraries, in information technology and media. There are also experts and practitioners, such as librarians, who serve on NISO working groups, committees, and as officers of the association. 

I myself personally have never served on NISO, but I’ve attended some of their meetings and their webinars. Developing standards is an interesting process to watch as they debate the minutiae of the technical and encoding standards that we just take for granted in our information retrieval systems. But this, again, is something that you as an information professional could become involved in. 

So, for example, you might be involved in creating standards for developing controlled vocabularies that are used in multiple contexts, or in bibliographic control structures, such as the new standard that we hope will replace MARC in the coming years. So, there are different ways in which you can become involved in this process. 
:::

## Who: International Standards Organization (ISO)

- World's largest developer and publisher of international standards 
- Founded in 1947 
- ISO has published more than 21,840 International Standards, ranging from standards for activities such as agriculture, construction, and mechanical engineering, to medical devices, to the newest information technology developments 

:::notes
The International Standards Organization, or ISO, is the world’s largest developer and publisher of international standards. You’ll often find standards that have been developed at a national level are then further refined at an international level through the ISO community.

ISO was founded in 1947, and they have published as of 2024, 25564 international standards that range from “activities such as agriculture to construction, mechanical engineering, … medical devices,” to those we’re most concerned about, “information technology developments.” They have a whole host of different standards supporting each of these different areas and more. 
:::




